Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 90

AllCops:
  TargetRubyVersion: 3.2.2
  DisplayCopNames: true
  Exclude:
    - 'spec/dummy/config/**/*'
    - 'spec/dummy/db/**/*'
