version: '3.9'
services:
  db:
    build: ./docker/postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rei_replication_test
      - POSTGRES_PASSWORD=changeme
      # - POSTGRES_USER=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  web:
    build: .
    image: rails-on-docker:1.3.0
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:changeme@db
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - HISTFILE=/usr/src/app/.dockerdev/.bash_history
      - MALLOC_ARENA_MAX=2
    volumes:
      - .:/usr/src/app/:cached
    depends_on:
      - db
volumes:
  bundle:
  db_data:
